name: A workflow for my Hello World App
on:
  push:
      branches:
        - master

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

#  IntegrationTests:
#    name: Integration Tests
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Integration Tests
#        run: |
#          docker build -t database ./db
#          docker run --name employees -dp 33060:3306 database
#          mvn -Dtest=com.napier.sem.AppIntegrationTest test
#          docker stop employees
#          docker rm employees
#          docker image rm database
#      - name: CodeCov
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
#          directory: ./target/site/jacoco
#          flags: Integration Tests # optional
#          verbose: true # optional (default = false)
#          slug: shakad72/sem

  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            automatic_release_tag: "latest"
            files: |
              ./target/*.jar
      - name: Copy Output
        run: docker container cp sem_app_1:./tmp/reports ./
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports # The branch the action should deploy to.
          folder: reports # The folder we are copying